feat: allow custom image fit property
konstantinmuenster/gatsby-theme-portfolio-minimal pull request #37
Opened 2023-04-11 17:45 UTC by Xstoudi

2023-04-14 06:00 UTC, konstantinmuenster requested changes
Only a small little change to make! Will need to test it locally, but looks good overall!

Thanks for contributing! Really appreciate it 👏☺️

2023-04-14 06:00 UTC, konstantinmuenster commented on gatsby-theme-portfolio-minimal/src/components/Project/index.tsx
> +
This could be removed 😄

2023-04-15 07:51 UTC, konstantinmuenster requested changes
Just tested it locally - works great! Could you have a look at the small comments I made, thanks!

And it would be great to add this new feature to the `gatsby-theme-portfolio-minimal/README.md` 🙏

2023-04-15 07:51 UTC, konstantinmuenster commented on gatsby-theme-portfolio-minimal/src/components/ArticleCard/index.tsx
> +                            objectFit={props.data.image.objectFit || 'cover'}
Can we remove the fallback `|| 'cover'`?

So you are able to specify no "object-fit" at all if you don't want to

2023-04-15 07:51 UTC, konstantinmuenster commented on gatsby-theme-portfolio-minimal/src/components/Project/index.tsx
> +                        objectFit={props.data.image.objectFit || 'cover'}
Can we remove the fallback `|| 'cover'`?

So you are able to specify no "object-fit" at all if you don't want to

2023-04-15 07:51 UTC, konstantinmuenster commented on gatsby-theme-portfolio-minimal/src/components/Project/index.tsx
> +                    objectFit={props.data.image.objectFit || 'cover'}
Can we remove the fallback `|| 'cover'`?

So you are able to specify no "object-fit" at all if you don't want to

2023-04-19 10:59 UTC, Xstoudi commented
I'm not really sure about what to write in the README for that ahah, I'm open to suggestions.

2023-04-24 06:43 UTC, konstantinmuenster commented
> I'm not really sure about what to write in the README for that ahah, I'm open to suggestions.

hm, true. There is currently no section that really fits. You could instead add the new prop to all section boilerplates files you find [in here](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/gatsby-theme-portfolio-minimal/content/sections). Just want to make sure that new users know this prop exists.

So, for example, for the `contact.example.json`:

```json
{
    "name": "",
    "email": "",
    "description": "",
    "image": {
        "src": "",
        "alt": "",
        "objectFit": ""
    },
    "socialProfiles": {
        "from": [""],
        "showIcons": true
    }
}
```

2023-04-25 06:35 UTC, Xstoudi commented
Make sense, I did it, let me know if anything else is needed.

2023-04-27 04:55 UTC, merged

2023-04-27 04:55 UTC, konstantinmuenster commented
Thank you very much for contributing! :)